# -*- coding: utf-8 -*-
"""Python_Dice_GAMES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CoKHDdboedC_UxC1_pdL6N0Nezy6iThM
"""

#dice game using pandas


import pandas
import random
def roll_dice():
  min=1
  max=6
  roll=random.randint(min,max)
  return roll
while True:
  player=input('Enter Number of Players :  ')
  print()
  if player.isdigit():
      player=int(player)
      if 1<=player<=5:
        break
      else:
          print('Please enter a number between 1 to 5')
  else:
    print('Not A Digit')
score=pandas.Series(0,index=range(1,player+1))
max_score=50
for i in range(1,player+1):
  print(f'Player number {i}')
  print()
  while True:
    should_roll=input("Do You wanna roll? (y/n) : ")
    if should_roll=='y':
      roll=roll_dice()
      print(f'Dice shows : {roll}')
      print()
      if roll==6:
        print(' "You rolled a SIX game over" ')
        print()
        break
      elif score[i]>=50:
        score[i]=50
        print("YAY! YOU HAVE REACHED THE MAX SCORE ")
        break
      else:
        score[i]=score[i]+roll

      print(f"current score is {score[i]}")
      print()
print('THE FINAL SCORE CHART IS :')
print(score)

win_score=max(score)
win_id=score.idxmax()
print(f'WINNER OF THE GAME IS : {win_id} , SCORE = {win_score}' )