# -*- coding: utf-8 -*-
"""transformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xan1ifzWhd5YtflWZr5sAw5CNLlbjGw6
"""

!pip install transformers

from transformers import pipeline
sa=pipeline('sentiment-analysis')
expression=input('enter the expression')
emotion={'NEGATIVE':'SAD','POSITIVE':'JOY','NEUTRAL':'NEUTRAL'}
result=sa(expression)
emotional_result=emotion[result[0]['label']]
print(emotional_result)

